trigger:
  - none
  
pool: 'Azure Pipelines'

resources:
  repositories:
  - repository: github-repo
    type: github
    name: memoliyasti/todowithflask
    endpoint: memoliyasti

parameters: 
  - name: Namespace
    displayName: Deployment Namespace
    type: string
    default: default

steps:
  - task: HelmInstaller@0
    displayName: 'Install Helm'
    inputs:
      version: '3.x'
  - task: HelmFetch@0
    displayName: 'Fetch nginx Helm chart'
    inputs:
      repository: 'https://kubernetes-charts.storage.googleapis.com'
      chart: 'nginx-ingress'
  - task: AzureCLI@2
    displayName: 'Authenticate to AKS'
    inputs:
      azureSubscription: 'todo-sc'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az login
        az aks get-credentials --name todo-k8s --resource-group todo-rg
  - task: HelmDeploy@0
    displayName: 'Install nginx Helm chart to AKS'
    inputs:
      command: 'install'
      chartType: 'FilePath'
      chartPath: 'nginx-ingress/'
      releaseName: 'nginx-ingress'
      namespace: 'default'
