trigger:
  - none
  
pool: 'Azure Pipelines'

parameters: 
  - name: Namespace
    displayName: Deployment Namespace
    type: string
    default: default

stages:
  - stage: Secrets
    displayName: Generate K8s Secrets
    jobs:
      - job: Secrets
        displayName: Generate Connector Secrets
        variables:
          - name: deploymentService
            value: 'todo-environment' 
          - name: aksClusterRg
            value: "todo-rg"
          - name: aksName
            value: "todo-k8s"
          - name: aksSC
            value: "todo-sc"
        steps:
          - checkout: none
          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(aksSC)
              azureResourceGroup: $(aksClusterRg)
              kubernetesCluster: $(aksName)
              useClusterAdmin: true
              namespace: $(Namespace) 
              secretType: 'generic'
              secretArguments: 'username=todo password=todo'
              secretName: 'aks-todo'