trigger:
  - none
  
pool: 'Azure Pipelines'

resources:
  repositories:
  - repository: github-repo
    type: github
    name: memoliyasti/todowithflask
    endpoint: memoliyasti

parameters:
  - name: Environment
    displayName: Environment
    type: string
    default: 'dev'

  - name: chartVersion
    displayName: Chart Version
    type: string
    default: "0.3.0"  
  - name: Namespace
    displayName: Deployment Namespace
    type: string
    default: default

variables:
  - name: chartPath
    value: "helm/todo"
  - name: chartName
    value: "todo"
  - name: releaseName
    value: todo-release

stages:
  - stage: Deploy
    displayName: (${{ parameters.Environment }}) - Deploy ${{ variables.chartName }}
    jobs:
    - job: Deploy
      steps:
      - task: HelmInstaller@1
        inputs:
          version: latest
      - task: HelmDeploy@0
        inputs:
          connectionType: AzureResourceManager
          azureSubscription: 'todo-sc'
          kubernetesCluster: 'todo-k8s'
          command: upgrade
          chartType: Repo
          chartName: ${{ variables.chartName }}
          chartVersion: ${{ parameters.chartVersion }}
          repoName: memoliyasti/todowithflask
          repoUrl: https://github.com/memoliyasti/todowithflask
          releaseName: ${{ variables.releaseName }}
          namespace: ${{ variables.namespace }}
          install: true
          force: true
          wait: true
  