trigger:
  - none
  
pool: 'Azure Pipelines'

parameters: 
  - name: Namespace
    displayName: Deployment Namespace
    type: string
    default: default

stages:
  - stage: Secrets
    displayName: Generate K8s Secrets
    jobs:
      - job: Secrets
        displayName: Generate Connector Secrets
        variables:
          - name: deploymentService
            value: 'todo-environment' 
          - name: aksClusterRg
            value: "todo-rg"
          - name: aksName
            value: "todo-k8s"
          - name: aksSC
            value: "todo-sc"
        steps:
          - checkout: none
          - task: Kubernetes@1
            inputs:
              connectionType: ${{ variables.aksSC }}}
              azureSubscriptionEndpoint: ${{ variables.deploymentService }}
              azureResourceGroup: ${{ variables.aksClusterRg }}
              kubernetesCluster: ${{ variables.aksName }}
              useClusterAdmin: true
              namespace: '${{ parameters.Namespace }}' 
              secretType: 'generic'
              secretName: 'todo-secret'
              command: 'create'