apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: memoliyasti/todo-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5001
