apiVersion: v1
kind: Service
metadata:
  name: todo-app
spec:
  selector:
    app: todo-app
  ports:
  - port: 32763
    targetPort: 5001
    nodePort: 32763
    protocol: TCP
    name: http
  type: NodePort
