name: Todo-Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Docker image version
        id: docker-image-version
        uses: docker/metadata-action@v3
        with:
          images: memoliyasti/todo
          flavor: |
            latest=true
            suffix=-${{ github.sha }}
      - name: Docker Tool Installer
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: 20.10.2
          docker_channel: stable

      - name: Build the Docker image
        run: docker build ./ -t memoliyasti/todo:${{ steps.docker-image-version.outputs.version }}
        env:
          IMAGE_VERSION: ${{ steps.docker-image-version.outputs.version }}

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u memoliyasti --password-stdin

      - name: Push the Docker image
        run: docker push memoliyasti/todo:${{ steps.docker-image-version.outputs.version }}

      - name: Set the image tag in the deployment file
        run: |
          sed -i 's|memoliyasti/todo:latest|memoliyasti/todo:${{ steps.docker-image-version.outputs.version }}|g' k8s/deployment.yaml
          cat k8s/deployment.yaml